"""Chinese-first MVP XHS seed candidates for destination coverage."""

from __future__ import annotations

from typing import Any

MVP_XHS_TARGET_CITIES = (
    "Shanghai",
    "Guangzhou",
    "Tokyo",
    "Kyoto",
    "Osaka",
    "Seoul",
    "Taipei",
    "Hong Kong",
    "Singapore",
    "Bangkok",
    "Paris",
    "London",
    "New York",
)


def _seed(candidate: str, category: str, destination: str, *aliases: str) -> dict[str, Any]:
    return {
        "candidate": candidate,
        "category": category,
        "destinations": [destination],
        "aliases": list(aliases),
        "queries": [],
    }


MVP_XHS_QUERY_ITEMS: list[dict[str, Any]] = [
    # Shanghai
    _seed("小杨生煎", "food", "Shanghai", "Yang's Dumplings"),
    _seed("佳家汤包", "food", "Shanghai"),
    _seed("莱莱小笼", "food", "Shanghai"),
    _seed("大壶春", "food", "Shanghai"),
    _seed("光明邨大酒家", "food", "Shanghai"),
    _seed("国际饭店蝴蝶酥", "food", "Shanghai"),
    _seed("新荣记上海", "food", "Shanghai", "新荣记"),
    _seed("愚园路", "attraction", "Shanghai"),
    _seed("武康路", "attraction", "Shanghai"),
    _seed("安福路", "attraction", "Shanghai"),
    _seed("巨富长街区", "attraction", "Shanghai", "巨鹿路", "富民路", "长乐路"),
    _seed("豫园城隍庙", "attraction", "Shanghai", "豫园", "城隍庙"),
    _seed("外滩", "attraction", "Shanghai"),
    _seed("新天地", "attraction", "Shanghai"),
    _seed("田子坊", "attraction", "Shanghai"),
    # Guangzhou
    _seed("银记肠粉", "food", "Guangzhou"),
    _seed("陈添记鱼皮", "food", "Guangzhou"),
    _seed("顺记冰室", "food", "Guangzhou"),
    _seed("吴财记面家", "food", "Guangzhou"),
    _seed("向群饭店", "food", "Guangzhou"),
    _seed("文记壹心鸡", "food", "Guangzhou"),
    _seed("惠食佳", "food", "Guangzhou"),
    _seed("莲香楼", "food", "Guangzhou"),
    _seed("广州酒家", "food", "Guangzhou"),
    _seed("北京路", "attraction", "Guangzhou", "北京路步行街"),
    _seed("永庆坊", "attraction", "Guangzhou"),
    _seed("沙面", "attraction", "Guangzhou"),
    _seed("东山口", "attraction", "Guangzhou"),
    _seed("白云山", "attraction", "Guangzhou"),
    _seed("广州塔珠江夜游", "attraction", "Guangzhou", "广州塔", "珠江夜游"),
    # Tokyo
    _seed("筑地场外市场", "food", "Tokyo", "築地場外市場"),
    _seed("月岛文字烧", "food", "Tokyo", "月島もんじゃ"),
    _seed("新宿思出横丁", "food", "Tokyo", "思い出横丁"),
    _seed("惠比寿横丁", "food", "Tokyo"),
    _seed("浅草寺", "attraction", "Tokyo"),
    _seed("上野阿美横町", "attraction", "Tokyo", "アメ横"),
    _seed("谷中银座", "attraction", "Tokyo"),
    _seed("吉祥寺井之头公园", "attraction", "Tokyo", "井之头公园"),
    _seed("下北泽", "attraction", "Tokyo"),
    _seed("中目黑", "attraction", "Tokyo"),
    _seed("神乐坂", "attraction", "Tokyo"),
    _seed("根津神社", "attraction", "Tokyo"),
    _seed("人形町今半", "food", "Tokyo"),
    _seed("代官山茑屋书店", "attraction", "Tokyo"),
    _seed("东京站拉面街", "food", "Tokyo"),
    # Kyoto
    _seed("锦市场", "food", "Kyoto"),
    _seed("出町双叶", "food", "Kyoto", "出町ふたば"),
    _seed("中村藤吉本店", "food", "Kyoto"),
    _seed("茶寮都路里", "food", "Kyoto"),
    _seed("键善良房", "food", "Kyoto", "鍵善良房"),
    _seed("京都智能咖啡", "drink", "Kyoto", "Smart Coffee", "スマート珈琲店"),
    _seed("清水寺二年坂", "attraction", "Kyoto", "二年坂", "三年坂"),
    _seed("伏见稻荷大社", "attraction", "Kyoto"),
    _seed("岚山竹林", "attraction", "Kyoto", "岚山"),
    _seed("鸭川纳凉床", "attraction", "Kyoto", "鸭川"),
    _seed("祇园白川", "attraction", "Kyoto"),
    _seed("哲学之道", "attraction", "Kyoto"),
    _seed("南禅寺", "attraction", "Kyoto"),
    _seed("京都御苑", "attraction", "Kyoto"),
    _seed("一保堂茶铺", "drink", "Kyoto", "一保堂"),
    # Osaka
    _seed("黑门市场", "food", "Osaka"),
    _seed("道顿堀", "food", "Osaka"),
    _seed("新世界串炸", "food", "Osaka", "新世界", "串炸"),
    _seed("法善寺横丁", "food", "Osaka"),
    _seed("天满市场", "food", "Osaka"),
    _seed("天神桥筋商店街", "food", "Osaka"),
    _seed("鹤桥烤肉", "food", "Osaka"),
    _seed("自由轩咖喱", "food", "Osaka"),
    _seed("会津屋章鱼烧", "food", "Osaka", "会津屋"),
    _seed("551蓬莱", "food", "Osaka"),
    _seed("通天阁", "attraction", "Osaka"),
    _seed("难波八阪神社", "attraction", "Osaka"),
    _seed("梅田蓝天大厦", "attraction", "Osaka"),
    _seed("北滨咖啡街", "drink", "Osaka", "北滨"),
    _seed("中崎町", "attraction", "Osaka"),
    # Seoul
    _seed("明洞饺子", "food", "Seoul", "명동교자"),
    _seed("广藏市场", "food", "Seoul", "광장시장"),
    _seed("南大门市场", "food", "Seoul", "남대문시장"),
    _seed("望远市场", "food", "Seoul", "망원시장"),
    _seed("通仁市场", "food", "Seoul", "통인시장"),
    _seed("弘大", "attraction", "Seoul", "홍대"),
    _seed("延南洞咖啡街", "drink", "Seoul", "延南洞", "연남동"),
    _seed("圣水洞", "attraction", "Seoul", "성수동"),
    _seed("益善洞韩屋街", "attraction", "Seoul", "익선동"),
    _seed("北村韩屋村", "attraction", "Seoul", "북촌한옥마을"),
    _seed("景福宫", "attraction", "Seoul", "경복궁"),
    _seed("汉南洞", "attraction", "Seoul", "한남동"),
    _seed("梨泰院", "attraction", "Seoul", "이태원"),
    _seed("乙支路", "attraction", "Seoul", "을지로"),
    _seed("新沙洞林荫道", "attraction", "Seoul", "가로수길"),
    # Taipei
    _seed("阜杭豆浆", "food", "Taipei"),
    _seed("永康牛肉面", "food", "Taipei"),
    _seed("鼎泰丰信义本店", "food", "Taipei", "鼎泰丰本店"),
    _seed("宁夏夜市", "food", "Taipei"),
    _seed("饶河夜市", "food", "Taipei"),
    _seed("师大夜市", "food", "Taipei"),
    _seed("西门町", "attraction", "Taipei"),
    _seed("迪化街", "attraction", "Taipei"),
    _seed("大稻埕", "attraction", "Taipei"),
    _seed("象山步道", "attraction", "Taipei"),
    _seed("猫空", "attraction", "Taipei"),
    _seed("华山1914文创园", "attraction", "Taipei", "华山1914"),
    _seed("松山文创园", "attraction", "Taipei"),
    _seed("九份老街", "attraction", "Taipei"),
    _seed("龙山寺", "attraction", "Taipei"),
    # Hong Kong
    _seed("华嫂冰室", "food", "Hong Kong"),
    _seed("九记牛腩", "food", "Hong Kong"),
    _seed("麦奀云吞面", "food", "Hong Kong"),
    _seed("澳洲牛奶公司", "food", "Hong Kong"),
    _seed("兰芳园", "food", "Hong Kong"),
    _seed("一乐烧鹅", "food", "Hong Kong"),
    _seed("添好运", "food", "Hong Kong"),
    _seed("佳佳甜品", "food", "Hong Kong"),
    _seed("深水埗", "attraction", "Hong Kong"),
    _seed("大馆", "attraction", "Hong Kong"),
    _seed("PMQ元创方", "attraction", "Hong Kong", "元创方"),
    _seed("西营盘", "attraction", "Hong Kong"),
    _seed("上环", "attraction", "Hong Kong"),
    _seed("庙街夜市", "food", "Hong Kong"),
    _seed("太平山顶", "attraction", "Hong Kong"),
    # Singapore
    _seed("天天海南鸡饭", "food", "Singapore"),
    _seed("亚坤", "food", "Singapore", "亚坤咖椰吐司"),
    _seed("松发肉骨茶", "food", "Singapore"),
    _seed("老巴刹", "food", "Singapore", "Lau Pa Sat"),
    _seed("麦士威熟食中心", "food", "Singapore", "Maxwell Food Centre"),
    _seed("中峇鲁市场", "food", "Singapore"),
    _seed("牛车水美食街", "food", "Singapore", "牛车水"),
    _seed("小印度", "attraction", "Singapore"),
    _seed("哈芝巷", "attraction", "Singapore"),
    _seed("甘榜格南", "attraction", "Singapore"),
    _seed("滨海湾花园", "attraction", "Singapore"),
    _seed("鱼尾狮公园", "attraction", "Singapore"),
    _seed("星耀樟宜", "attraction", "Singapore", "Jewel Changi"),
    _seed("娘惹菜蓝姜", "food", "Singapore", "Blue Ginger"),
    _seed("阿秋甜品", "food", "Singapore"),
    # Bangkok
    _seed("Jeh O Chula", "food", "Bangkok", "朱拉隆功妈妈面", "朱拉妈妈面", "妈妈面"),
    _seed("Thipsamai", "food", "Bangkok", "Thipsamai Pad Thai", "Thipsamai泰式炒粉"),
    _seed("Jay Fai", "food", "Bangkok", "杰菲", "痣姐"),
    _seed("水门鸡饭", "food", "Bangkok"),
    _seed("建兴酒家", "food", "Bangkok", "Somboon Seafood"),
    _seed("曼谷唐人街耀华力路", "food", "Bangkok", "耀华力路"),
    _seed("恰图恰周末市场", "attraction", "Bangkok"),
    _seed("ICONSIAM", "attraction", "Bangkok", "暹罗天地"),
    _seed("郑王庙", "attraction", "Bangkok"),
    _seed("大皇宫", "attraction", "Bangkok"),
    _seed("卧佛寺", "attraction", "Bangkok"),
    _seed("暹罗商圈", "attraction", "Bangkok", "Siam"),
    _seed("曼谷旧城区咖啡", "drink", "Bangkok"),
    _seed("Talat Noi", "attraction", "Bangkok", "曼谷老城 Talat Noi"),
    _seed("王权云顶大厦", "attraction", "Bangkok", "Mahanakhon"),
    # Paris
    _seed("埃菲尔铁塔", "attraction", "Paris"),
    _seed("卢浮宫", "attraction", "Paris"),
    _seed("奥赛博物馆", "attraction", "Paris"),
    _seed("蒙马特", "attraction", "Paris"),
    _seed("玛黑区", "attraction", "Paris"),
    _seed("圣日耳曼德佩", "attraction", "Paris"),
    _seed("拉丁区", "attraction", "Paris"),
    _seed("塞纳河游船", "attraction", "Paris"),
    _seed("杜乐丽花园", "attraction", "Paris"),
    _seed("巴黎歌剧院", "attraction", "Paris"),
    _seed("花神咖啡馆", "drink", "Paris", "Cafe de Flore"),
    _seed("双叟咖啡馆", "drink", "Paris", "Les Deux Magots"),
    _seed("天使娜热巧克力", "drink", "Paris", "Angelina"),
    _seed("皮埃尔艾尔梅马卡龙", "food", "Paris", "Pierre Herme"),
    _seed("巴黎左岸咖啡", "drink", "Paris"),
    # London
    _seed("大英博物馆", "attraction", "London"),
    _seed("伦敦塔桥", "attraction", "London"),
    _seed("博罗市场", "food", "London", "Borough Market"),
    _seed("考文特花园", "attraction", "London"),
    _seed("诺丁山波托贝洛市场", "attraction", "London", "Portobello Market"),
    _seed("肖迪奇", "attraction", "London", "Shoreditch"),
    _seed("南岸", "attraction", "London", "South Bank"),
    _seed("小威尼斯", "attraction", "London", "Little Venice"),
    _seed("空中花园", "attraction", "London", "Sky Garden"),
    _seed("格林尼治", "attraction", "London"),
    _seed("Dishoom印度餐厅", "food", "London", "Dishoom"),
    _seed("Flat Iron牛排", "food", "London", "Flat Iron"),
    _seed("Padella意面", "food", "London", "Padella"),
    _seed("Fortnum Mason下午茶", "drink", "London", "Fortnum & Mason"),
    _seed("Sketch下午茶", "drink", "London", "Sketch"),
    # New York
    _seed("中央公园", "attraction", "New York"),
    _seed("大都会艺术博物馆", "attraction", "New York"),
    _seed("纽约现代艺术博物馆", "attraction", "New York", "MoMA"),
    _seed("高线公园", "attraction", "New York"),
    _seed("切尔西市场", "food", "New York", "Chelsea Market"),
    _seed("布鲁克林大桥", "attraction", "New York"),
    _seed("DUMBO", "attraction", "New York", "丹波"),
    _seed("西村", "attraction", "New York", "West Village"),
    _seed("苏豪区", "attraction", "New York", "SoHo"),
    _seed("纽约公共图书馆", "attraction", "New York"),
    _seed("Katz熟食店", "food", "New York", "Katz's Delicatessen"),
    _seed("Levain Bakery曲奇", "food", "New York", "Levain Bakery"),
    _seed("Joe's Pizza", "food", "New York", "纽约披萨 Joe's Pizza"),
    _seed("Los Tacos No.1", "food", "New York", "纽约墨西哥卷饼"),
    _seed("法拉盛主街", "food", "New York", "Flushing Main Street"),
]
